/* Auto-generated by genmsg_cpp for file /opt/ros/cturtle/stacks/ccny-ros-pkg/ccny_ground_station/gpsd_viewer/msg/cmd.msg */
#ifndef GPSD_VIEWER_MESSAGE_CMD_H
#define GPSD_VIEWER_MESSAGE_CMD_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace gpsd_viewer
{
template <class ContainerAllocator>
struct cmd_ : public ros::Message
{
  typedef cmd_<ContainerAllocator> Type;

  cmd_()
  : header()
  , distance(0.0)
  , angle(0.0)
  {
  }

  cmd_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , distance(0.0)
  , angle(0.0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef double _distance_type;
  double distance;

  typedef double _angle_type;
  double angle;


private:
  static const char* __s_getDataType_() { return "gpsd_viewer/cmd"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1e702fa4e6381467e6c9d2dde0bc2a3d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 distance\n\
float64 angle\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, angle);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, angle);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(angle);
    return size;
  }

  typedef boost::shared_ptr< ::gpsd_viewer::cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpsd_viewer::cmd_<ContainerAllocator>  const> ConstPtr;
}; // struct cmd
typedef  ::gpsd_viewer::cmd_<std::allocator<void> > cmd;

typedef boost::shared_ptr< ::gpsd_viewer::cmd> cmdPtr;
typedef boost::shared_ptr< ::gpsd_viewer::cmd const> cmdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gpsd_viewer::cmd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gpsd_viewer::cmd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gpsd_viewer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::gpsd_viewer::cmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e702fa4e6381467e6c9d2dde0bc2a3d";
  }

  static const char* value(const  ::gpsd_viewer::cmd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e702fa4e6381467ULL;
  static const uint64_t static_value2 = 0xe6c9d2dde0bc2a3dULL;
};

template<class ContainerAllocator>
struct DataType< ::gpsd_viewer::cmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gpsd_viewer/cmd";
  }

  static const char* value(const  ::gpsd_viewer::cmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gpsd_viewer::cmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 distance\n\
float64 angle\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::gpsd_viewer::cmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::gpsd_viewer::cmd_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gpsd_viewer::cmd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.distance);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct cmd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpsd_viewer::cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gpsd_viewer::cmd_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GPSD_VIEWER_MESSAGE_CMD_H

